dm_protein = 'MENNEAPSPSGSNNNENNNAAQKKLQQTQAKVDEVVGIMRVNVEKVLERDQKLSELGE\
            RADQLEQGASQFEQQAGKLKRKQWWANMKMMIILGVIAVVLLIIVLVSLFN'

dm_rna = 'ATGGAGAACAACGAAGCCCCCTCCCCCTCGGGATCCAACAACAACGAGAACAACAATGCAGC\
        CCAGAAGAAGCTGCAGCAGACCCAAGCCAAGGTGGACGAGGTGGTCGGGATTATGCGTGTGAACGTGGAGAA\
        GGTCCTGGAGCGGGACCAGAAGCTATCGGAACTGGGCGAGCGTGCGGATCAGCTGGAGCAGGGAGCATCCCA\
        GTTCGAGCAGCAGGCCGGCAAGCTGAAGCGCAAGCAATGGTGGGCCAACATGAAGATGATGATCATTCTGGG\
        CGTGATAGCCGTTGTGCTGCTCATCATCGTTCTGGTGTCGCTTTTCAATTGA'

import finding_codons
import pytest

import finding_codons

def test_finding_codons():
    assert finding_codon.find_codonlesson6('TTT', 'ATTT') == -1

    return 
